cursor #88d1eb
cursor_text_color #003543

selection_foreground #cfe6f1
selection_background #344a52

active_tab_foreground #dee3e6
active_tab_background #353a3c
inactive_tab_foreground #bfc8cc
inactive_tab_background #0a0f11

# Normal colors
color0  #0f1416
color1  #ffb4ab
color2  #88d1eb
color3  #c3c3eb
color4  #b3cad4
color5  #8a9296
color6  #004e60
color7  #dee3e6

# Foreground/Background
foreground #dee3e6
background #0f1416
