##############################
### ENVIRONTMENT VARIABLES ###
##############################

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = QT_QUICK_CONTROLS_STYLE,Material
env = QT_STYLE_OVERRIDE,Breeze-Dark
