#############
### EXECS ###
#############

exec-once = awww-daemon
exec-once = swaync
exec-once = hyprpm
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --tpye image --watch cliphist store
exec-once = ~/.local/bin/loginnotify.sh
exec-once = ~/.config/cached/birthday.sh
exec-once = swayosd-server
exec-once = nm-applet
exec-once = blueman-applet
exec-once = quickshell
