##############
### OTHERS ###
##############

dwindle {
    pseudotile = true 
    preserve_split = true 
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = -1 
    disable_hyprland_logo = false 
}

monitor=,preffered,auto,1
#monitor=VGA-1,preffered,auto,0.8
permission = /usr/(bin|local/bin)/hyprpm, plugin, allow

plugin:dynamic-cursors {

    mode = stretch
    # apply a 90° offset in rotate mode to the text shape
    shaperule = text, rotate:offset: 360

    # use stretch mode when grabbing, and set the limit low
    shaperule = grab, stretch, stretch:limit: 2000

    # do not show any effects on clientside cursors
    shaperule = clientside, none
}
