################
### PROGRAMS ###
################

$terminal = kitty
$fileManager = nautilus
$app = ./.config/rofi/launchers/type-1/launcher.sh
$themr = ./.config/rofi/applets/bin/themer.sh
$hyprlock = hyprlock
$applet = ./.config/rofi/applets/bin/apps.sh
