####################
### WINDOW RULES ###
####################

### SECTION : Window rules

#windowrule = match:class .*, size 800 400
windowrule = match:class yad, float on, size 500 50
windowrule = match:class Alacritty, size 800 400, center on
windowrule = match:class kitty, size 800 400
windowrule = match:class Dolphin, opacity 0.85 0.85
windowrule = match:class Spotify, opacity 0.85 0.85
windowrule = dim_around on, match:class yad
windowrule = match:class yad, pin on
windowrule = match:class xdg-desktop-portal-gtk, float on, size 800 400
windowrule = match:class cava-term, workspace 2
windowrule = match:class cava-term, float on
windowrule = match:class cava-term, size 800 300
windowrule = match:class cava-term, move 2216 538

### .= Layerrules

layerrule = blur on, match:namespace quickshell
layerrule = ignore_alpha 0.7, match:namespace quickshell

