##################
### EVERY CONF ###
##################

### DIVIDED BY : Importance

# VERY IMPORTANT (MUST START)
source = ~/.config/hypr/configs/settings/execs.conf
source = ~/.config/hypr/configs/settings/look.conf
source = ~/.config/hypr/configs/settings/program.conf
source = ~/.config/hypr/configs/settings/keymaps.conf

# IMPORTANT (MUST START)
source = ~/.config/hypr/configs/settings/devices.conf
source = ~/.config/hypr/configs/settings/animations.conf
source = ~/.config/hypr/configs/settings/others.conf

# NORMAL (CAN START)
source = ~/.config/hypr/configs/settings/envar.conf
source = ~/.config/hypr/configs/settings/rules.conf

